Grant alter to Developer2
grant connect to Developer2
grant control to Developer2
grant create CONTRACT to Developer2
GRANT CREATE MESSAGE TYPE TO Developer2
GRANT CREATE PROCEDURE TO Developer2
GRANT CREATE QUEUE TO Developer2
GRANT CREATE SERVICE TO Developer2
GRANT EXECUTE TO Developer2
GRANT SELECT TO Developer2
GRANT SUBSCRIBE QUERY NOTIFICATIONS TO Developer2
GRANT VIEW DATABASE STATE TO Developer2
GRANT VIEW DEFINITION TO Developer2

ALTER DATABASE commerce_bank SET SINGLE_USER WITH ROLLBACK IMMEDIATE
ALTER DATABASE commerce_bank SET ENABLE_BROKER;
ALTER DATABASE commerce_bank SET MULTI_USER WITH ROLLBACK IMMEDIATE